######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 24 12:12:30 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
