######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 24 12:03:57 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
